name: Build and Deploy
on:
  push:
    branches: [main]

env:
  ASPNETCORE_ENVIRONMENT: Production
  PROJECT_PRODUCT_CATALOG: src/ProductCatalog/ProductCatalog.csproj
  REGISTRY_NAME: 'sshsconrgs01.azurecr.io'
  DB_CONNECTION_STRING: Host=${{ secrets.DB_HOST }}.postgres.database.azure.com;Port=${{ secrets.DB_PORT }};Username=${{ secrets.DB_ADMIN_USERNAME }}@${{ secrets.DB_HOST }};Password=${{ secrets.DB_ADMIN_PASSWORD }};Database=${{ secrets.DB_NAME }};

jobs:
  path-filters:
    runs-on: ubuntu-latest
    outputs:
      terraformPath: ${{steps.filter.outputs.terraform}}
      productCatPath: ${{steps.filter.outputs.prodcat}}
    
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            iac:
              - 'iac/**'
            productcat:
              - 'src/ProductCatalog/**'

      - name: terraform tests
        if: steps.filter.outputs.iac == 'true'
        run: echo "IaC path is triggered"

      - name: prod cat tests
        if: steps.filter.outputs.productcat == 'true'
        run: echo "ProductCatalog path is triggered"

  infrastructure:
    runs-on: ubuntu-latest
    needs: path-filters
    #if: needs.path-filters.outputs.iac == 'true'
    steps:
      - name: output
        run: echo ${{needs.path-filters.outputs}}

      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./iac/main.bicep
          parameters: 'dockerRegistryUsername=${{ secrets.SANDBOXCR01_USERNAME_BFD8 }} dockerRegistryPassword=${{secrets.SANDBOXCR01_PASSWORD_BFD8}} dbAdminUser=${{secrets.AZURE_DB_ADMINUSER}} dbAdminPassword=${{secrets.AZURE_DB_ADMINPASSWORD}}'
  
  productcat:
    runs-on: ubuntu-latest
    needs: infrastructure
    if: needs.path-filters.outputs.productCatPath == 'true'
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: "Login into Azure Container Registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.SANDBOXCR01_USERNAME_BFD8SANDBOXCR01_USERNAME_BFD8 }}
          password: ${{ secrets.SANDBOXCR01_PASSWORD_BFD8 }}

      - name: "Pushing docker image to ACR"
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }} -f src/ProductCatalog/Docker/Dockerfile src/ProductCatalog
          docker push ${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }}

      - name: "Push image to web app"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sshsappsrvcat01"
          images: "${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }}"
      
      - name: Azure logout
        run: |
          az logout