name: Build and Deploy
on:
  push:
    branches: [main]

env:
  ASPNETCORE_ENVIRONMENT: Development
  PROJECT_PRODUCT_CATALOG: src/ProductCatalog/ProductCatalog.csproj
  REGISTRY_NAME: 'sshsconrgs01.azurecr.io'

jobs:
  path-filters:
    runs-on: ubuntu-latest
    outputs:
      iac: ${{steps.filter.outputs.iac}}
      productCat: ${{steps.filter.outputs.productcat}}
    
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            iac:
              - 'iac/**'
            productcat:
              - 'src/ProductCatalog/**'

  infrastructure:
    runs-on: ubuntu-latest
    needs: path-filters
    if: ${{ needs.path-filters.outputs.iac == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: centralus
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./iac/main.bicep
          parameters: 'dockerRegistryUsername=${{ secrets.AZURE_ACR_USERNAME }} dockerRegistryPassword=${{secrets.AZURE_ACR_PASSWORD}} dbAdminUser=${{secrets.AZURE_DB_ADMINUSER}} dbAdminPassword=${{secrets.AZURE_DB_ADMINPASSWORD}}'
  
  productcat:
    runs-on: ubuntu-latest
    needs: [path-filters, infrastructure]
    if: ${{ needs.path-filters.outputs.productCat == 'true' }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: "Login into Azure Container Registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.SANDBOXCR01_USERNAME_BFD8SANDBOXCR01_USERNAME_BFD8 }}
          password: ${{ secrets.SANDBOXCR01_PASSWORD_BFD8 }}

      - name: "Pushing docker image to ACR"
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }} -f src/ProductCatalog/Docker/Dockerfile src/ProductCatalog
          docker push ${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }}

      - name: "Push image to web app"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sshsappsrvcat01"
          images: "${{ env.REGISTRY_NAME }}/productcatalog:${{ github.sha }}"
      
      - name: Azure logout
        run: |
          az logout